import * as Joi from 'joi';

export const configSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'staging', 'production').default('development'),
  AUTH_DELIVERY_MODE: Joi.string().valid('email', 'console', 'disabled').default('console'),
  AUTH_DEV_BYPASS_ENABLED: Joi.boolean().default(false),
  AUTH_DEV_BYPASS_EMAIL: Joi.string().email().optional(),
  AUTH_DEV_BYPASS_CODE: Joi.string().optional(),
  AUTH_DEV_BYPASS_LINK_TOKEN: Joi.string().optional(),
  AUTH_LINK_BASE_URL: Joi.string().uri().optional(),
  AUTH_REVIEW_EMAIL: Joi.string().email().optional(),
  AUTH_REVIEW_CODE: Joi.string().optional(),
  PORT: Joi.number().default(3000),
  DATABASE_URL: Joi.string().required(),
  JWT_SECRET: Joi.string().min(32).required(),
  JWT_EXPIRY: Joi.string().default('15m'),
  REFRESH_TOKEN_EXPIRY_DAYS: Joi.number().default(30),
  MAGIC_LINK_EXPIRY_MINUTES: Joi.number().default(15),
  REDIS_URL: Joi.string().default('redis://localhost:6379'),
  SMTP_HOST: Joi.string().optional(),
  SMTP_PORT: Joi.number().default(587),
  SMTP_USER: Joi.string().optional(),
  SMTP_PASS: Joi.string().optional(),
  SMTP_FROM: Joi.string().email().default('noreply@yourapp.com'),
  RESEND_API_KEY: Joi.string().optional(),
  ALLOWED_ORIGINS: Joi.string().optional(),
  APP_URL: Joi.string().uri().optional(),
  WEB_APP_URL: Joi.string().uri().optional(),
  WEB_ADMIN_URL: Joi.string().uri().optional(),
  WEB_PUBLIC_URL: Joi.string().uri().optional(),
  MEILISEARCH_URL: Joi.string().uri().optional(),
  MEILISEARCH_KEY: Joi.string().optional(),
  R2_ACCOUNT_ID: Joi.string().optional(),
  R2_ACCESS_KEY_ID: Joi.string().optional(),
  R2_SECRET_ACCESS_KEY: Joi.string().optional(),
  R2_BUCKET_NAME: Joi.string().optional(),
  R2_PUBLIC_BASE_URL: Joi.string().uri().optional(),
  APP_VERSION_IOS_CURRENT: Joi.string().default('1.0.0'),
  APP_VERSION_IOS_MINIMUM: Joi.string().default('1.0.0'),
  APP_VERSION_ANDROID_CURRENT: Joi.string().default('1.0.0'),
  APP_VERSION_ANDROID_MINIMUM: Joi.string().default('1.0.0'),
  GOOGLE_CLIENT_ID: Joi.string().optional(),
  GOOGLE_IOS_CLIENT_ID: Joi.string().optional(),
  GOOGLE_ANDROID_CLIENT_ID: Joi.string().optional(),
  GOOGLE_WEB_CLIENT_ID: Joi.string().optional(),
  APPLE_BUNDLE_ID: Joi.string().optional(),
});
